build:
  image: stronglytyped/arm-none-eabi-gcc
  script:
    - mkdir build
    - cd build/
    - cmake ..
    - make binary
  artifacts:
    paths:
      - build/tiva_code.elf
      - build/tiva_code.bin